name: Publish pages

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Add system dependencies
        run: |
          sudo apt install python3-build
      - name: Add Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools build
      - name: Add pygments-pasp for pasp syntax highlighting
        run: |
          pip install pygments-pasp
      - name: Compile HTML pages with pymdpages
        run: |
          python -m pymdpages.pymdpages.pymdpages *.md
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: out/

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1

